### ISSUE TITLE
Anonymous functions inside data-bind

### ISSUE THREAD

**Issue by nkosi23** [knockout/tko#91]
Hello,

Thanks for the great work!

I read in the Patreon page that tko wouldn't be backward compatible as far as anonymous functions in data-bind are concerned. 

This is a pattern that we used quite extensively to prevent the data-bind code from executing immediately. I will need to triple check more deeply to ensure that the problem cannot be solved by referencing $root.myfunction in data-bind without the () parenthesis indicating a function call. But if I remember correctly, we tested and were only able to get the correct behavior by using an anonymous function. 

But maybe this is a bug with the framework we use (proposing HTML components with knockout integration). Everytime we use their onClick binding, we need to use an anonymous function for the reason stated above. I am not sure this is the case with the standard click binding (but we cannot bypass their framework since we need their framework to handle event management in order to let it update their components etc...)

Apart from that, this pattern was also useful to pass multiple parameters from the binding context to a function of the viewModel. I am wondering if tko will provide an alternative syntax for this feature or if the feature will be totally dropped (which would cause us to scratch our head).

Thank you

**Comment by brianmhunt** [comment]
Hi @nkosi23 thanks for the post.

Knockout used to use `eval` to call functions, whereas TKO uses a variant of [`knockout-secure-binding`](https://github.com/brianmhunt/knockout-secure-binding), which should work with lambdas i.e. `data-bind="click: () => doThing()"`.  This is partly to support content-security-policies, but also because [javascript `with` is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with).

There's a rewrite plugin as well that changes ``data-bind="click: function () { doThing() }"` to `data-bind="click: () => doThing()"`.

What TKO doesn't support (at least right now) is the use of complex functions e.g. `data-bind="() => { x + 1; y + 2 }"`

If there were demand it wouldn't be overwhelming to add support for the prior `eval`-style of data-binding.

Does that help?

**Comment by nkosi23** [comment]
Many thanks for your swift reply!
This is indeed helpful, however the problem I see is that older browsers like internet explorer do not support lambda expressions.

You also raise my attention on something, I wasn't aware of the situation with "with". Does this mean that the with binding will no longer be able to work? This binding is massively helpful.

**Comment by brianmhunt** [comment]
The safest way to abound the lambda problem is to define and reference functions on the data/component/root model by name.  Note that if tko works in IE then lambdas will work since tko embeds it’s own javascript parser.

The with binding itself is fine, but the underlying JavaScript syntax/ `with` used for all bindings is discouraged/prohibited in some JavaScript modes.  This makes it less future proof, though it’s doubtful the `with` keyword will be removed in the foreseeable future owing to the need for backwards compatibility.

**Comment by nkosi23** [comment]
Thank you very much for these insights
